name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: make    
    - name: apt install libllvm-dev
      run: make
    - name: test
      run: ./bfc /programms/hello.bf out.ll && clang -o hello out.ll && ./hello
